// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package http

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Defines values for ProcessStatuses.
const (
	Failed   ProcessStatuses = "failed"
	Finished ProcessStatuses = "finished"
	Working  ProcessStatuses = "working"
)

// ProcessStatuses Process Status
type ProcessStatuses string

// UserSchema User object
type UserSchema struct {
	Birthday string `json:"birthday"`
	Id       uint64 `json:"id"`
	Name     string `json:"name"`
}

// Error defines model for Error.
type Error struct {
	Code    float32 `json:"code"`
	Message string  `json:"message"`
	Time    float32 `json:"time"`
	TraceId string  `json:"traceId"`
}

// GetGoogleCredentials defines model for GetGoogleCredentials.
type GetGoogleCredentials struct {
	Link string `json:"link"`
}

// GetLogged defines model for GetLogged.
type GetLogged struct {
	AllowActions *string `json:"allowActions,omitempty"`
	Email        string  `json:"email"`
	Id           string  `json:"id"`
	IsAdmin      bool    `json:"isAdmin"`
	Role         string  `json:"role"`
	Token        string  `json:"token"`
}

// GetProcessStatus defines model for GetProcessStatus.
type GetProcessStatus struct {
	Complete bool   `json:"complete"`
	Date     uint64 `json:"date"`
	Detail   string `json:"detail"`

	// Id Process Status
	Id ProcessStatuses `json:"id"`
}

// GetUser User object
type GetUser = UserSchema

// GetUsers defines model for GetUsers.
type GetUsers = []UserSchema

// ReqGoogleToken defines model for ReqGoogleToken.
type ReqGoogleToken struct {
	Token string `json:"token"`
}

// ReqLogin defines model for ReqLogin.
type ReqLogin struct {
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// ReqSignIn defines model for ReqSignIn.
type ReqSignIn struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Username string `json:"username"`
}

// ReqUser User object
type ReqUser = UserSchema

// ReqUserFilter defines model for ReqUserFilter.
type ReqUserFilter struct {
	Birthday string `json:"birthday"`
	Name     string `json:"name"`
}

// SetCrossfitTokenJSONBody defines parameters for SetCrossfitToken.
type SetCrossfitTokenJSONBody struct {
	Token string `json:"token"`
}

// LoginJSONBody defines parameters for Login.
type LoginJSONBody struct {
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// SignInJSONBody defines parameters for SignIn.
type SignInJSONBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Username string `json:"username"`
}

// FilterUsersJSONBody defines parameters for FilterUsers.
type FilterUsersJSONBody struct {
	Birthday string `json:"birthday"`
	Name     string `json:"name"`
}

// SetCrossfitTokenJSONRequestBody defines body for SetCrossfitToken for application/json ContentType.
type SetCrossfitTokenJSONRequestBody SetCrossfitTokenJSONBody

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// SignInJSONRequestBody defines body for SignIn for application/json ContentType.
type SignInJSONRequestBody SignInJSONBody

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = UserSchema

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UserSchema

// FilterUsersJSONRequestBody defines body for FilterUsers for application/json ContentType.
type FilterUsersJSONRequestBody FilterUsersJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Start booking
	// (POST /crossfit/start)
	StartBookingCrossfit(ctx echo.Context) error
	// Get status process booking
	// (GET /crossfit/status)
	GetCrossfitStatus(ctx echo.Context) error
	// Get URI token
	// (GET /crossfit/token)
	GetCrossfitToken(ctx echo.Context) error
	// Set token
	// (POST /crossfit/token)
	SetCrossfitToken(ctx echo.Context) error
	// Login to page
	// (POST /login)
	Login(ctx echo.Context) error
	// Sign in
	// (POST /signin)
	SignIn(ctx echo.Context) error
	// Create new user
	// (POST /user)
	CreateUser(ctx echo.Context) error
	// Delete user
	// (DELETE /user/{id})
	DeleteUser(ctx echo.Context, id int) error
	// Get an user by its id
	// (GET /user/{id})
	GetUser(ctx echo.Context, id int) error
	// Update an user by its id
	// (PUT /user/{id})
	UpdateUser(ctx echo.Context, id int) error
	// Returns all users
	// (GET /users)
	GetUsers(ctx echo.Context) error
	// Search users using filters
	// (POST /users)
	FilterUsers(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// StartBookingCrossfit converts echo context to params.
func (w *ServerInterfaceWrapper) StartBookingCrossfit(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.StartBookingCrossfit(ctx)
	return err
}

// GetCrossfitStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GetCrossfitStatus(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetCrossfitStatus(ctx)
	return err
}

// GetCrossfitToken converts echo context to params.
func (w *ServerInterfaceWrapper) GetCrossfitToken(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetCrossfitToken(ctx)
	return err
}

// SetCrossfitToken converts echo context to params.
func (w *ServerInterfaceWrapper) SetCrossfitToken(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SetCrossfitToken(ctx)
	return err
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Login(ctx)
	return err
}

// SignIn converts echo context to params.
func (w *ServerInterfaceWrapper) SignIn(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SignIn(ctx)
	return err
}

// CreateUser converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateUser(ctx)
	return err
}

// DeleteUser converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteUser(ctx, id)
	return err
}

// GetUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUser(ctx, id)
	return err
}

// UpdateUser converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateUser(ctx, id)
	return err
}

// GetUsers converts echo context to params.
func (w *ServerInterfaceWrapper) GetUsers(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUsers(ctx)
	return err
}

// FilterUsers converts echo context to params.
func (w *ServerInterfaceWrapper) FilterUsers(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.FilterUsers(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/crossfit/start", wrapper.StartBookingCrossfit)
	router.GET(baseURL+"/crossfit/status", wrapper.GetCrossfitStatus)
	router.GET(baseURL+"/crossfit/token", wrapper.GetCrossfitToken)
	router.POST(baseURL+"/crossfit/token", wrapper.SetCrossfitToken)
	router.POST(baseURL+"/login", wrapper.Login)
	router.POST(baseURL+"/signin", wrapper.SignIn)
	router.POST(baseURL+"/user", wrapper.CreateUser)
	router.DELETE(baseURL+"/user/:id", wrapper.DeleteUser)
	router.GET(baseURL+"/user/:id", wrapper.GetUser)
	router.PUT(baseURL+"/user/:id", wrapper.UpdateUser)
	router.GET(baseURL+"/users", wrapper.GetUsers)
	router.POST(baseURL+"/users", wrapper.FilterUsers)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8yYW2/buBLHvwrBcx4VS07TxvLTSduzQXaL3UXTPhVBQYsji65Eqrw0awT67gteZMuy",
	"HN+23T4UUW1e/vObP4cjP+FMVLXgwLXC0ycs4asBpV8LysB98B6+3goxL+GD+ALcfpIJroFr+0jqumQZ",
	"0UzweKGE+1plBVTEPtVS1CB1WEi38/WyBjzFSkvG57hpIrcpk0Dx9FMY9hC1w8RsAZnGjR1HQWWS1XY7",
	"PMVOENICEaML4NoKAdxdTUsDTWRDeCfm7BzxNVHqUUhqn+EvUtWl1UZmN28n158n1zjqRxVho0ByUsHm",
	"lIUoOBUwTpPtOc1A0F7+PZvzu3P0Q0VY2VcC/wv/G2WiGgphOOqbyeJzWv3Ojwl6z1Y9D3i1nf07Cz/s",
	"hPRRgTwK0X8l5HiK/xOvj0Dsv1WxXezejxywnv0WtfuvNv+FlfpICZtZmjGpC0qWm/QukyS5SNKL8eUQ",
	"8W3av4qC70XspkXrHQexujmqFlx5ff+XUpwTXyboptbLJFnty001A2lDqkApMu9FVdoTjMApGMCgWQ/D",
	"+OWr6zRN04H1tSQZ3PVcffni5WVCFM3DvyRPknwymewl2apdrxvURD7eQ0qZA9sx1C1oX3TfSKC2tJFS",
	"ncG9ZPzL/srrRh2i1ktD2VobaiF47e/EfA70DMGkLMXjTWbHqgHh0VA9C0/7ahrr5T2dXKcmTUyaXJhl",
	"aki+UPQiJ0YJepEbIhRlg8uoG1r5K2W1Vk5KBauxMyFKINwOlqLsuZkyCZneYeX2ouzEZpWlC7rIyUJR",
	"scjJKLfSilyQwv0piBIjSMWjexaFoiIvFkSogi7ysiB7bex3dXyiVQFuowwhHGIOn3tkNivkLeg/pchA",
	"qXtNtFFnFRELRTugFHJiSv0Mekr8yFzIimg8xYZx/epqjYNxDXNfFyjo4KodrnnuwtgID9QWX8eV+g4l",
	"bBRh5WFE66AOQRy2QmG2x/vv3X5h8+NyyjRU6hgZKy5ESrLcJctzD/Pt8v20ONMMwbxvUwHcVDZhj0J+",
	"sdmPcM44UwXYBOaElUA7WVpbpCN2a5MusegfuPR7RWwcHeTvE1sF59xD+oUIM56L4egVAk5rwbh216N2",
	"2/uMRfgbSOWHJqPxKLFaRQ2c1AxP8YtRMnrhmkFdOGBxJoVSOdOx0kQ6r9VCub+Wq3Ocvd3xvf36tRA2",
	"jW/CHNxraS6Tq23Bf/zmbWSqishluxKa+aVsAGSuLJpWCX6w4zeEhSI3hwFht6BbPSvb9VQlu87Galy8",
	"VVM3Nd+CDhUC1cHjhwewuoP26f8Qro2T5G/3ONshfHx/h9q7aUB1tCv3QxLbV9vlbnWdt9+49+rbHGId",
	"ZTKLOjclWgmyM68OQeL76ybCL48YvWlU0M/Rsjku21fhYXD+Tfk0Wn5uc6IbQtd4NKwrn4fvjdYFh7RA",
	"dej2A17P07NVbM6fgxve40+jGyYfZEM7FjGOgh1/WqhBZwdnQOh5mtDUDNN8I4FocI3PaUTd1G2e44Ps",
	"2k7+QSfbB4s4PLreukPMuFt0DSx+YrTxlmj75E1ub93nK277vOSaF7/Wz3s6fUy70EQ777FhCsl3dMAP",
	"AmLvTsL9e9hsiZhWyDVy22hqIkkF2nXwn/rJv3uLRI50sULbbTptqXN9WdsgTn2zuPkLbNRp+/tNafMQ",
	"4doMpOZjTb/L2d7lb+P2+3n97XkclNG2Djzbf7at98nGV2eF8x60kVwhUpbIBCkDzhws+/5n1nUAp3kj",
	"/Fjb/NCzf0ZfR2RWeFTIKMbnKHcBDIFzU0F+a0+0kSWe4kLrehrHpchIWQilp0+1kLqJv41j3Dw0fwcA",
	"AP//9F4CZgkaAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
