- name: backend
  description: "backend"
  color: bfd4f2
- name: frontend
  description: "frontend"
  color: 7b3479
- name: infra
  description: "infra"
  color: 1d76db
- name: docs
  description: "docs"
  color: a2eeef
- name: schema
  description: "schema"
  color: a2eeef
- name: ci
  description: "ci system"
  color: ededed
- name: proxy
  description: "proxy system"
  color: 1d76db
- name: proxybot
  description: "proxy telegram system"
  color: 1d76db
- name: renovate/Major
  description: "renovate/Major"
  color: 1e1e1e
- name: renovate/Minor
  description: "renovate/Minor"
  color: 1e1e1e
- name: renovate/Patch
  description: "renovate/Patch"
  color: 1e1e1e
- name: renovate/Security
  description: "renovate/Security"
  color: f00000