// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Defines values for ProcessStatuses.
const (
	Failed   ProcessStatuses = "failed"
	Finished ProcessStatuses = "finished"
	Working  ProcessStatuses = "working"
)

// ProcessStatuses Process Status
type ProcessStatuses string

// UserSchema User object
type UserSchema struct {
	Birthday string `json:"birthday"`
	Id       uint64 `json:"id"`
	Name     string `json:"name"`
}

// Error defines model for Error.
type Error struct {
	Code    float32 `json:"code"`
	Message string  `json:"message"`
	Time    float32 `json:"time"`
	TraceId string  `json:"traceId"`
}

// GoogleCredentials defines model for GoogleCredentials.
type GoogleCredentials struct {
	Link string `json:"link"`
}

// Logged defines model for Logged.
type Logged struct {
	AllowActions *string `json:"allowActions,omitempty"`
	Email        string  `json:"email"`
	Id           string  `json:"id"`
	IsAdmin      bool    `json:"isAdmin"`
	Role         string  `json:"role"`
	Token        string  `json:"token"`
}

// ProcessStatus defines model for ProcessStatus.
type ProcessStatus struct {
	Complete bool   `json:"complete"`
	Date     uint64 `json:"date"`
	Detail   string `json:"detail"`

	// Id Process Status
	Id ProcessStatuses `json:"id"`
}

// User User object
type User = UserSchema

// Users defines model for Users.
type Users = []UserSchema

// GoogleToken defines model for GoogleToken.
type GoogleToken struct {
	Token string `json:"token"`
}

// Login defines model for Login.
type Login struct {
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// SignIn defines model for SignIn.
type SignIn struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Username string `json:"username"`
}

// UserFilter defines model for UserFilter.
type UserFilter struct {
	Birthday string `json:"birthday"`
	Name     string `json:"name"`
}

// SetCrossfitTokenJSONBody defines parameters for SetCrossfitToken.
type SetCrossfitTokenJSONBody struct {
	Token string `json:"token"`
}

// LoginJSONBody defines parameters for Login.
type LoginJSONBody struct {
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// SignInJSONBody defines parameters for SignIn.
type SignInJSONBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Username string `json:"username"`
}

// FilterUsersJSONBody defines parameters for FilterUsers.
type FilterUsersJSONBody struct {
	Birthday string `json:"birthday"`
	Name     string `json:"name"`
}

// SetCrossfitTokenJSONRequestBody defines body for SetCrossfitToken for application/json ContentType.
type SetCrossfitTokenJSONRequestBody SetCrossfitTokenJSONBody

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// SignInJSONRequestBody defines body for SignIn for application/json ContentType.
type SignInJSONRequestBody SignInJSONBody

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = UserSchema

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UserSchema

// FilterUsersJSONRequestBody defines body for FilterUsers for application/json ContentType.
type FilterUsersJSONRequestBody FilterUsersJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Start booking
	// (POST /crossfit/start)
	StartBookingCrossfit(ctx echo.Context) error
	// Get status process booking
	// (GET /crossfit/status)
	GetCrossfitStatus(ctx echo.Context) error
	// Get URI token
	// (GET /crossfit/token)
	GetCrossfitToken(ctx echo.Context) error
	// Set token
	// (POST /crossfit/token)
	SetCrossfitToken(ctx echo.Context) error
	// Login to page
	// (POST /login)
	Login(ctx echo.Context) error
	// Sign in
	// (POST /signin)
	SignIn(ctx echo.Context) error
	// Create new user
	// (POST /user)
	CreateUser(ctx echo.Context) error
	// Delete user
	// (DELETE /user/{id})
	DeleteUser(ctx echo.Context, id int) error
	// Get an user by its id
	// (GET /user/{id})
	GetUser(ctx echo.Context, id int) error
	// Update an user by its id
	// (PUT /user/{id})
	UpdateUser(ctx echo.Context, id int) error
	// Returns all users
	// (GET /users)
	GetUsers(ctx echo.Context) error
	// Search users using filters
	// (POST /users)
	FilterUsers(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// StartBookingCrossfit converts echo context to params.
func (w *ServerInterfaceWrapper) StartBookingCrossfit(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.StartBookingCrossfit(ctx)
	return err
}

// GetCrossfitStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GetCrossfitStatus(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetCrossfitStatus(ctx)
	return err
}

// GetCrossfitToken converts echo context to params.
func (w *ServerInterfaceWrapper) GetCrossfitToken(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetCrossfitToken(ctx)
	return err
}

// SetCrossfitToken converts echo context to params.
func (w *ServerInterfaceWrapper) SetCrossfitToken(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SetCrossfitToken(ctx)
	return err
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Login(ctx)
	return err
}

// SignIn converts echo context to params.
func (w *ServerInterfaceWrapper) SignIn(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SignIn(ctx)
	return err
}

// CreateUser converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateUser(ctx)
	return err
}

// DeleteUser converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteUser(ctx, id)
	return err
}

// GetUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUser(ctx, id)
	return err
}

// UpdateUser converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateUser(ctx, id)
	return err
}

// GetUsers converts echo context to params.
func (w *ServerInterfaceWrapper) GetUsers(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUsers(ctx)
	return err
}

// FilterUsers converts echo context to params.
func (w *ServerInterfaceWrapper) FilterUsers(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.FilterUsers(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/crossfit/start", wrapper.StartBookingCrossfit)
	router.GET(baseURL+"/crossfit/status", wrapper.GetCrossfitStatus)
	router.GET(baseURL+"/crossfit/token", wrapper.GetCrossfitToken)
	router.POST(baseURL+"/crossfit/token", wrapper.SetCrossfitToken)
	router.POST(baseURL+"/login", wrapper.Login)
	router.POST(baseURL+"/signin", wrapper.SignIn)
	router.POST(baseURL+"/user", wrapper.CreateUser)
	router.DELETE(baseURL+"/user/:id", wrapper.DeleteUser)
	router.GET(baseURL+"/user/:id", wrapper.GetUser)
	router.PUT(baseURL+"/user/:id", wrapper.UpdateUser)
	router.GET(baseURL+"/users", wrapper.GetUsers)
	router.POST(baseURL+"/users", wrapper.FilterUsers)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8yYW3PbNhOG/woG33dJi5TjxKKu6iRtxm2n7cTJVcaTgYilCIUEWBziajz87x0cKFEU",
	"ZZ2S1BceUyIO7z77crHUI85EVQsOXCs8fcQS/jag9GtBGbgv3gkxL+GD+ALcfswE18C1vSR1XbKMaCZ4",
	"vFDC3VZZARWxV7UUNUgdVtHtfL2sAU+x0pLxOW6ayO3IJFA8/RSG3UftMDFbQKZxY8dRUJlktd0OT7ET",
	"hLRAxOgCuLZCAHdX09JAE+HfxZydo7wmSj0ISe01/EOqurTCyOzm7eT68+QaR/2QImwUSE4q2JyyEAWn",
	"AsZpsj2nGYi4ifAdm/Pbc8RDRVjZlwE/hU+jTFRD+odDvpksPqfVH/yYiPds1cu+V9vZv7Pw/TChjwrk",
	"UXz+LyHHU/y/eG372N9VsV3szo8ccJy9i9rN/c6/sFIfuf9mfmZM6oKS5Sa3yyRJLpL0Ynw5xHqb86+i",
	"4HvhumnResdBoG6OqgVXXt/PUopz4ssE3dR6mSSrfbmpZiBtSBUoRea9qEr74CJwCgYwaNbDMH756jpN",
	"03RgfS1JBrc9P1++eHmZEEXz8JfkSZJPJpO9JFu163WDmsjHe0j5cmA7bvJV9o0EamsZKdUZ0EvGv+wv",
	"tW7UIVK9NJSttaGWgC+vc6BnqCVlKR5uMjtWDaiOhmpYuNpXx1gv4+nkOjVpYtLkwixTQ/KFohc5MUrQ",
	"i9wQoSgbXEbd0MqfIau1clIqWI2dCVEC4XawFGXPx5RJyPQOE7fHYic2qyxd0EVOFoqKRU5GuZVW5IIU",
	"7l9BlBhBKh7ctSgUFXmxIEIVdJGXBdlrYL+r4xOtim4bZQjhEGf43COzWRj/kiIDpe400UadVTssEe1o",
	"UsiJKfUT3CnxI3MhK6LxFBvG9aurNQvGNcx9OaCgg6V2WOapQ2IjPFBbcB1U6puRsFGElYcRrYM6hG/Y",
	"CoXZ//lxd1w2mYZKHaNhRYRISZa7NHniYb5dvp8QZ5chjHdtEoCbyqbqQcgvNu8RzhlnqgCbupywEmgn",
	"P2tzdMRubdLFFX2DU75Xu8bRQc4+sTdwnj2kQYgw47kYjl4h4LQWjGt3Hmq3vc9YhL+CVH5oMhqPEqtV",
	"1MBJzfAUvxgloxeu79OFAxZnUiiVMx0rTaTzWi2U+2+5OsfZ4xzf2duvhbBpfBPm4F4Pc5lcbQv+8zdv",
	"I1NVRC7bldDML2UDIHNl0bRK8L0dvyEslLc5DAh7B7rVs7JdT1Wy69lYjdusNT3B70CHwoDqYPDD1a/O",
	"nX3iP4Sj4njt2x3Ntv6P729RexgNSI52ZX1IX/vautwtrfNmG3dfa5tDHKNMZiHnpkQrNXbm1SEwfB/d",
	"RPjlEaM3/Qn6KVQ2u2X7pjtMzb8In4DKT2xOMUHoDo/GdOUz8L2husiQFqgO/XwA60l6qorN+VNYwzv6",
	"CVzDzIPcZ8cixlFw4bMlGnR2WAZ+HqYJ/cswyjcSiAbX45yA083bhjneH0g78wc9yj5MxOHBtc4dVsad",
	"lmtU8SOjjTdD2wlvEnvrvl8R2+ci16T4tZ7vQ+lj2oUm2nlkDVNIvlf6fxANe0wS7t+xZkvEtEKuW9vm",
	"UhNJKtCuTf/Uz/ztWyRypIsV125nacuba77aLnDqO8LN31KjTm/f7zyb+wjXZiAvH2v67R/pXc42brPn",
	"62wP46B0thXgyQ6zba5Ps7w6K5b3oI3kCpGyRCboGPDkYJ33P5uu1Z/givDLa/PjnvczOjcis8JDQkYx",
	"Pke5Uz+EzE0F+bV9io0s8RQXWtfTOC5FRspCKD19rIXUTfx1HOPmvvk3AAD//y/ZrxLEGQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
