//
//Crossfit Agenda
//
//No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
//The version of the OpenAPI document: 1.0.0
//
//Generated by OpenAPI Generator: https://openapi-generator.tech

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: service/handlers/grpc/crossfitagenda.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Process Status
type Status200Response_IdEnum int32

const (
	Status200Response_IdEnum_WORKING  Status200Response_IdEnum = 0
	Status200Response_IdEnum_FINISHED Status200Response_IdEnum = 1
	Status200Response_IdEnum_FAILED   Status200Response_IdEnum = 2
)

// Enum value maps for Status200Response_IdEnum.
var (
	Status200Response_IdEnum_name = map[int32]string{
		0: "IdEnum_WORKING",
		1: "IdEnum_FINISHED",
		2: "IdEnum_FAILED",
	}
	Status200Response_IdEnum_value = map[string]int32{
		"IdEnum_WORKING":  0,
		"IdEnum_FINISHED": 1,
		"IdEnum_FAILED":   2,
	}
)

func (x Status200Response_IdEnum) Enum() *Status200Response_IdEnum {
	p := new(Status200Response_IdEnum)
	*p = x
	return p
}

func (x Status200Response_IdEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status200Response_IdEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_service_handlers_grpc_crossfitagenda_proto_enumTypes[0].Descriptor()
}

func (Status200Response_IdEnum) Type() protoreflect.EnumType {
	return &file_service_handlers_grpc_crossfitagenda_proto_enumTypes[0]
}

func (x Status200Response_IdEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status200Response_IdEnum.Descriptor instead.
func (Status200Response_IdEnum) EnumDescriptor() ([]byte, []int) {
	return file_service_handlers_grpc_crossfitagenda_proto_rawDescGZIP(), []int{3, 0}
}

type CredentialsGoogle200Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link string `protobuf:"bytes,3321850,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *CredentialsGoogle200Response) Reset() {
	*x = CredentialsGoogle200Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_handlers_grpc_crossfitagenda_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CredentialsGoogle200Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsGoogle200Response) ProtoMessage() {}

func (x *CredentialsGoogle200Response) ProtoReflect() protoreflect.Message {
	mi := &file_service_handlers_grpc_crossfitagenda_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsGoogle200Response.ProtoReflect.Descriptor instead.
func (*CredentialsGoogle200Response) Descriptor() ([]byte, []int) {
	return file_service_handlers_grpc_crossfitagenda_proto_rawDescGZIP(), []int{0}
}

func (x *CredentialsGoogle200Response) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type SetTokenGoogleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,110541305,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *SetTokenGoogleRequest) Reset() {
	*x = SetTokenGoogleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_handlers_grpc_crossfitagenda_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTokenGoogleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTokenGoogleRequest) ProtoMessage() {}

func (x *SetTokenGoogleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_handlers_grpc_crossfitagenda_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTokenGoogleRequest.ProtoReflect.Descriptor instead.
func (*SetTokenGoogleRequest) Descriptor() ([]byte, []int) {
	return file_service_handlers_grpc_crossfitagenda_proto_rawDescGZIP(), []int{1}
}

func (x *SetTokenGoogleRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type StartCrossfitAgenda500Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32  `protobuf:"varint,355610639,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,418054152,opt,name=message,proto3" json:"message,omitempty"`
	Date    string `protobuf:"bytes,3076014,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *StartCrossfitAgenda500Response) Reset() {
	*x = StartCrossfitAgenda500Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_handlers_grpc_crossfitagenda_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartCrossfitAgenda500Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCrossfitAgenda500Response) ProtoMessage() {}

func (x *StartCrossfitAgenda500Response) ProtoReflect() protoreflect.Message {
	mi := &file_service_handlers_grpc_crossfitagenda_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCrossfitAgenda500Response.ProtoReflect.Descriptor instead.
func (*StartCrossfitAgenda500Response) Descriptor() ([]byte, []int) {
	return file_service_handlers_grpc_crossfitagenda_proto_rawDescGZIP(), []int{2}
}

func (x *StartCrossfitAgenda500Response) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *StartCrossfitAgenda500Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StartCrossfitAgenda500Response) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type Status200Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date     uint64                   `protobuf:"varint,3076014,opt,name=date,proto3" json:"date,omitempty"`
	Detail   string                   `protobuf:"bytes,261482417,opt,name=detail,proto3" json:"detail,omitempty"`
	Id       Status200Response_IdEnum `protobuf:"varint,3355,opt,name=id,proto3,enum=crossfitagenda.Status200Response_IdEnum" json:"id,omitempty"`
	Complete bool                     `protobuf:"varint,62574280,opt,name=complete,proto3" json:"complete,omitempty"`
}

func (x *Status200Response) Reset() {
	*x = Status200Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_handlers_grpc_crossfitagenda_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status200Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status200Response) ProtoMessage() {}

func (x *Status200Response) ProtoReflect() protoreflect.Message {
	mi := &file_service_handlers_grpc_crossfitagenda_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status200Response.ProtoReflect.Descriptor instead.
func (*Status200Response) Descriptor() ([]byte, []int) {
	return file_service_handlers_grpc_crossfitagenda_proto_rawDescGZIP(), []int{3}
}

func (x *Status200Response) GetDate() uint64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *Status200Response) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Status200Response) GetId() Status200Response_IdEnum {
	if x != nil {
		return x.Id
	}
	return Status200Response_IdEnum_WORKING
}

func (x *Status200Response) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

var File_service_handlers_grpc_crossfitagenda_proto protoreflect.FileDescriptor

var file_service_handlers_grpc_crossfitagenda_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x72, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x72, 0x6f, 0x73, 0x73, 0x66, 0x69, 0x74,
	0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x63, 0x72,
	0x6f, 0x73, 0x73, 0x66, 0x69, 0x74, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x1c, 0x43, 0x72, 0x65,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x32, 0x30,
	0x30, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x04, 0x6c, 0x69, 0x6e,
	0x6b, 0x18, 0xfa, 0xdf, 0xca, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b,
	0x22, 0x30, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x47, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0xf9, 0xf3, 0xda, 0x34, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0x71, 0x0a, 0x1e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x72, 0x6f, 0x73, 0x73,
	0x66, 0x69, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x35, 0x30, 0x30, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x8f,
	0xe0, 0xc8, 0xa9, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1c, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x88, 0x80, 0xac, 0xc7,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x15,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0xae, 0xdf, 0xbb, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0xe5, 0x01, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x32, 0x30, 0x30, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x18, 0xae, 0xdf, 0xbb, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x19, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0xb1, 0xcf, 0xd7,
	0x7c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x39, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x9b, 0x1a, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x63, 0x72, 0x6f,
	0x73, 0x73, 0x66, 0x69, 0x74, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x32, 0x30, 0x30, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x64,
	0x45, 0x6e, 0x75, 0x6d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x18, 0xc8, 0x9d, 0xeb, 0x1d, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x63,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x22, 0x44, 0x0a, 0x06, 0x49, 0x64, 0x45, 0x6e, 0x75,
	0x6d, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x64, 0x45, 0x6e, 0x75, 0x6d, 0x5f, 0x57, 0x4f, 0x52, 0x4b,
	0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x64, 0x45, 0x6e, 0x75, 0x6d, 0x5f,
	0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x45, 0x44, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x64,
	0x45, 0x6e, 0x75, 0x6d, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x02, 0x32, 0xc8, 0x02,
	0x0a, 0x0e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x59, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x47,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x2c, 0x2e,
	0x63, 0x72, 0x6f, 0x73, 0x73, 0x66, 0x69, 0x74, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x43,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x32, 0x30, 0x30, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0e, 0x53,
	0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x12, 0x25, 0x2e,
	0x63, 0x72, 0x6f, 0x73, 0x73, 0x66, 0x69, 0x74, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x53,
	0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x45, 0x0a, 0x13,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x66, 0x69, 0x74, 0x41, 0x67, 0x65,
	0x6e, 0x64, 0x61, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x43, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x21, 0x2e, 0x63, 0x72, 0x6f, 0x73, 0x73, 0x66, 0x69, 0x74,
	0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x30, 0x30,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x3b, 0x67,
	0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_handlers_grpc_crossfitagenda_proto_rawDescOnce sync.Once
	file_service_handlers_grpc_crossfitagenda_proto_rawDescData = file_service_handlers_grpc_crossfitagenda_proto_rawDesc
)

func file_service_handlers_grpc_crossfitagenda_proto_rawDescGZIP() []byte {
	file_service_handlers_grpc_crossfitagenda_proto_rawDescOnce.Do(func() {
		file_service_handlers_grpc_crossfitagenda_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_handlers_grpc_crossfitagenda_proto_rawDescData)
	})
	return file_service_handlers_grpc_crossfitagenda_proto_rawDescData
}

var file_service_handlers_grpc_crossfitagenda_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_handlers_grpc_crossfitagenda_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_service_handlers_grpc_crossfitagenda_proto_goTypes = []interface{}{
	(Status200Response_IdEnum)(0),          // 0: crossfitagenda.Status200Response.IdEnum
	(*CredentialsGoogle200Response)(nil),   // 1: crossfitagenda.CredentialsGoogle200Response
	(*SetTokenGoogleRequest)(nil),          // 2: crossfitagenda.SetTokenGoogleRequest
	(*StartCrossfitAgenda500Response)(nil), // 3: crossfitagenda.StartCrossfitAgenda500Response
	(*Status200Response)(nil),              // 4: crossfitagenda.Status200Response
	(*emptypb.Empty)(nil),                  // 5: google.protobuf.Empty
}
var file_service_handlers_grpc_crossfitagenda_proto_depIdxs = []int32{
	0, // 0: crossfitagenda.Status200Response.id:type_name -> crossfitagenda.Status200Response.IdEnum
	5, // 1: crossfitagenda.DefaultService.CredentialsGoogle:input_type -> google.protobuf.Empty
	2, // 2: crossfitagenda.DefaultService.SetTokenGoogle:input_type -> crossfitagenda.SetTokenGoogleRequest
	5, // 3: crossfitagenda.DefaultService.StartCrossfitAgenda:input_type -> google.protobuf.Empty
	5, // 4: crossfitagenda.DefaultService.Status:input_type -> google.protobuf.Empty
	1, // 5: crossfitagenda.DefaultService.CredentialsGoogle:output_type -> crossfitagenda.CredentialsGoogle200Response
	5, // 6: crossfitagenda.DefaultService.SetTokenGoogle:output_type -> google.protobuf.Empty
	5, // 7: crossfitagenda.DefaultService.StartCrossfitAgenda:output_type -> google.protobuf.Empty
	4, // 8: crossfitagenda.DefaultService.Status:output_type -> crossfitagenda.Status200Response
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_handlers_grpc_crossfitagenda_proto_init() }
func file_service_handlers_grpc_crossfitagenda_proto_init() {
	if File_service_handlers_grpc_crossfitagenda_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_handlers_grpc_crossfitagenda_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CredentialsGoogle200Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_handlers_grpc_crossfitagenda_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetTokenGoogleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_handlers_grpc_crossfitagenda_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartCrossfitAgenda500Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_handlers_grpc_crossfitagenda_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status200Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_handlers_grpc_crossfitagenda_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_handlers_grpc_crossfitagenda_proto_goTypes,
		DependencyIndexes: file_service_handlers_grpc_crossfitagenda_proto_depIdxs,
		EnumInfos:         file_service_handlers_grpc_crossfitagenda_proto_enumTypes,
		MessageInfos:      file_service_handlers_grpc_crossfitagenda_proto_msgTypes,
	}.Build()
	File_service_handlers_grpc_crossfitagenda_proto = out.File
	file_service_handlers_grpc_crossfitagenda_proto_rawDesc = nil
	file_service_handlers_grpc_crossfitagenda_proto_goTypes = nil
	file_service_handlers_grpc_crossfitagenda_proto_depIdxs = nil
}
