openapi: 3.0.3
info:
  title: Users
  description: Users endpoint
  version: 0.1.0

servers:
  - url: http://localhost:{port}/v1/

paths:
  /crossfit/token:
    get:
      summary: Get URI token
      operationId: GetCrossfitToken
      tags:
        - crossfit
      responses:
        '200':
          $ref: '#/components/responses/GetGoogleCredentials'
    post:
      summary: Set token
      operationId: SetCrossfitToken
      tags:
        - crossfit
      requestBody:
        $ref: '#/components/requestBodies/ReqGoogleToken'
      responses:
        204:
          description: successful operation
        400:
          $ref: '#/components/responses/Error'
        500:
          $ref: '#/components/responses/Error'
  /crossfit/start:
    post:
      summary: Start booking
      operationId: StartBookingCrossfit
      tags:
        - crossfit
      responses:
        '204':
          description: 'OK'
  /crossfit/status:
    get:
      summary: Get status process booking
      tags:
        - crossfit
      responses:
        '200':
          $ref: '#/components/responses/GetProcessStatus'

  /login:
    post:
      summary: Login to page
      operationId: Login
      tags:
        - login
      requestBody:
        $ref: '#/components/requestBodies/ReqLogin'
      responses:
        '200':
          $ref: '#/components/responses/GetLogged'
        '404':
          $ref: '#/components/responses/Error'
        '400':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'

  /signin:
    post:
      summary: Sign in
      operationId: SignIn
      tags:
        - signin
      requestBody:
        $ref: '#/components/requestBodies/ReqSignIn'
      responses:
        '204':
          description: Sign in success
        '404':
          $ref: '#/components/responses/Error'
        '400':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'

  /users:
    get:
      operationId: GetUsers
      tags:
        - users
      summary: Returns all users
      responses:
        '200':
          $ref: '#/components/responses/GetUsers'
        '500':
          $ref: '#/components/responses/Error'
    post:
      operationId: FilterUsers
      tags:
        - users
      summary: Search users using filters
      requestBody:
        $ref: '#/components/requestBodies/ReqUserFilter'
      responses:
        '200':
          $ref: '#/components/responses/GetUser'
        '400':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'

  /user:
    post:
      operationId: CreateUser
      tags:
        - users
      summary: Create new user
      requestBody:
        $ref: '#/components/requestBodies/ReqUser'
      responses:
        '201':
          $ref: '#/components/responses/GetUser'
        '400':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'

  /user/{id}:
    parameters:
      - name: id
        description: ID of the user
        in: path
        example: 1
        required: true
        schema:
          type: integer
    get:
      operationId: GetUser
      tags:
        - users
      summary: Get an user by its id
      responses:
        '200':
          $ref: '#/components/responses/GetUser'
        '404':
          $ref: '#/components/responses/Error'
        '400':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
    put:
      operationId: UpdateUser
      tags:
        - users
      summary: Update an user by its id
      requestBody:
        $ref: '#/components/requestBodies/ReqUser'
      responses:
        '204':
          description: User updated
        '404':
          $ref: '#/components/responses/Error'
        '400':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
    delete:
      operationId: DeleteUser
      tags:
        - users
      summary: Delete user
      responses:
        '204':
          description: User deleted
        '404':
          $ref: '#/components/responses/Error'
        '400':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'

components:

  schemas:

    UserSchema:
      description: User object
      type: object
      properties:
        id:
          type: integer
          format: uint64
          example: 1
        name:
          type: string
          example: 'John'
        birthday:
          type: string
          example: '2000-09-12'
      required:
        - id
        - name
        - birthday

    ProcessStatuses:
      type: string
      description: Process Status
      enum:
        - working
        - finished
        - failed

  responses:

    Error:
      description: Error object
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: number
                example: 200
              message:
                type: string
                example: login error
              time:
                type: number
                example: 15679999
              traceId:
                type: string
                example: 23520asdfasdfasd0f00f888
            required:
              - message
              - traceId
              - time
              - code
    
    GetUsers:
      description: Users
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/UserSchema'

    GetUser:
      description: User object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserSchema'

    GetLogged:
      description: Logged user object
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: string
                example: 9879u90u90-uy9uafjsd-fausod-fuaosdi
              email:
                type: string
                example: example@example.com
              isAdmin:
                type: boolean
                example: false
              role:
                type: string
                example: director
              allowActions:
                type: string
              token:
                type: string
                example: ey9ua9jdjfajsdojfa.faosdhfoahsdhfohaso.e9owhfohaohsdofhjaoshdjflha
            required:
              - token
              - id
              - email
              - isAdmin
              - role

    GetGoogleCredentials:
      description: Google credentials message
      content:
        application/json:
          schema:
            type: object
            properties:
              link:
                type: string
            required:
              - link

    GetProcessStatus:
      description: Process status
      content:
        application/json:
          schema:
            type: object
            properties:
              date:
                type: integer
                format: uint64
              detail:
                type: string
              id:
                $ref: '#/components/schemas/ProcessStatuses'
              complete:
                type: boolean
                default: false
            required:
              - id
              - date
              - detail
              - status
              - complete

  requestBodies:
    ReqLogin:
      content:
        application/json:
          schema:
            type: object
            properties:
              username:
                type: string
                example: johndoe190
              password:
                type: string
                example: abAD87_87

    ReqUser:
      description: User object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserSchema'

    ReqUserFilter:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                example: 'John'
              birthday:
                type: string
                example: '2000-09-12'
            required:
              - name
              - birthday

    ReqSignIn:
      content:
        application/json:
          schema:
            type: object
            properties:
              username:
                type: string
                example: joe@example.com
              password:
                type: string
                example: A8j_9mNn
              email:
                type: string
                example: joe@example.com
            required:
              - email
              - password
              - username

    ReqGoogleToken:
      required: true
      description: Token to authenticate
      content:
        application/json:
          schema:
            type: object
            properties:
              token:
                type: string
            required:
              - token