// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package http

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Defines values for ProcessStatuses.
const (
	Failed   ProcessStatuses = "failed"
	Finished ProcessStatuses = "finished"
	Working  ProcessStatuses = "working"
)

// ProcessStatuses Process Status
type ProcessStatuses string

// Error defines model for Error.
type Error struct {
	Date    string `json:"date"`
	Message string `json:"message"`
	Status  uint32 `json:"status"`
}

// GoogleCredentials defines model for GoogleCredentials.
type GoogleCredentials struct {
	Link string `json:"link"`
}

// ProcessStatus defines model for ProcessStatus.
type ProcessStatus struct {
	Complete bool   `json:"complete"`
	Date     uint64 `json:"date"`
	Detail   string `json:"detail"`

	// Id Process Status
	Id ProcessStatuses `json:"id"`
}

// GoogleToken defines model for GoogleToken.
type GoogleToken struct {
	Token string `json:"token"`
}

// SetTokenGoogleJSONBody defines parameters for SetTokenGoogle.
type SetTokenGoogleJSONBody struct {
	Token string `json:"token"`
}

// SetTokenGoogleJSONRequestBody defines body for SetTokenGoogle for application/json ContentType.
type SetTokenGoogleJSONRequestBody SetTokenGoogleJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get link to auth in Google
	// (GET /credentials/google)
	CredentialsGoogle(ctx echo.Context) error
	// Set token
	// (POST /credentials/google)
	SetTokenGoogle(ctx echo.Context) error
	// Start process to fill our calendar
	// (POST /start)
	StartCrossfitAgenda(ctx echo.Context) error
	// Status process
	// (GET /status)
	Status(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// CredentialsGoogle converts echo context to params.
func (w *ServerInterfaceWrapper) CredentialsGoogle(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CredentialsGoogle(ctx)
	return err
}

// SetTokenGoogle converts echo context to params.
func (w *ServerInterfaceWrapper) SetTokenGoogle(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SetTokenGoogle(ctx)
	return err
}

// StartCrossfitAgenda converts echo context to params.
func (w *ServerInterfaceWrapper) StartCrossfitAgenda(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.StartCrossfitAgenda(ctx)
	return err
}

// Status converts echo context to params.
func (w *ServerInterfaceWrapper) Status(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Status(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/credentials/google", wrapper.CredentialsGoogle)
	router.POST(baseURL+"/credentials/google", wrapper.SetTokenGoogle)
	router.POST(baseURL+"/start", wrapper.StartCrossfitAgenda)
	router.GET(baseURL+"/status", wrapper.Status)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6SVTW/bPAzHv4rA5zm6cdZ2O/i2FcMw7DIgOwwYdlBt2lEjS5pEbQgKf/eB8kucOkXT",
	"5eZIpPgj+SfzCKVtnTVoKEDxCB5/RQz0wVYK08EnaxuN3+wODf8srSE0xJ/SOa1KScqa/CHYdB3KLbaS",
	"v5y3Dj0Nr9DoT3uHUEAgr0wDXZeliMpjBcWPwexnNprZ+wcsCTq2qzCUXjkOBwUkIEFWyEhbNMQgCPPX",
	"yEfs3w/OmtBzfPTe+gvyqDjKMo0MWgxBNqfvAkmKyb22vpUEBURl6OYapkSVIWzQLwoyuB7ez3qEc0qU",
	"chWjY5cNrbzzWHHBpA4XFEIrs3u5n8nqHNYeTZQHtjn4V29LDGEz1fEfoVnqGvsOVljLqAmKWuqAE+K9",
	"tRql4ahjr4+a9u72RNM4G5JKn+y+qvj4f481FPBffhi3vMcM+VF6GBZVVNXY9ilQdlDGlNQ5dR5CicGb",
	"DQYKhnwKksp0yn0zBkcTW0b8Y/2O882gVkaFLTJyLZXGasY1U0nAMnpF+w1H70NJp77gnr8Ux9qirNBD",
	"Bka27Pz9Sjp1tcP9oQGDR8pTmdqm+ivSfHfnbQi1IvG+QVNJyOA3+tCn8Wa1Xq25N9ahkU5BATer9eoG",
	"MnCStokmn2kxb5I8+bjBpDpWVdLc5yrFmkx7IcOTtXO9Xj8ngskuX45nKlRsW+n3PCNIggdq3HpCGTGE",
	"6zJwNpwg2yClTTnDGvf7/nmi2V9APt//3SKt26VGQixZI3XUYmJhz9tzatDv5y6Dt6+wPqrSBkn0fyN8",
	"ngeSPtXlmfrw9SiVSSkvJ2l3l0FyWOGGaSIraqW1sNGLUmqG8BP9sPFO6m4aw9eL7XilLugohhGPx6v7",
	"GwAA///a+X8eJwgAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
