// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: proto/crossfitAgenda/crossfitagenda.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CrossfitAgendaServiceClient is the client API for CrossfitAgendaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CrossfitAgendaServiceClient interface {
	CredentialsGoogle(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CredentialsGoogle200Response, error)
	SetTokenGoogle(ctx context.Context, in *SetTokenGoogleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	StartCrossfitAgenda(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Status(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Status200Response, error)
}

type crossfitAgendaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCrossfitAgendaServiceClient(cc grpc.ClientConnInterface) CrossfitAgendaServiceClient {
	return &crossfitAgendaServiceClient{cc}
}

func (c *crossfitAgendaServiceClient) CredentialsGoogle(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CredentialsGoogle200Response, error) {
	out := new(CredentialsGoogle200Response)
	err := c.cc.Invoke(ctx, "/crossfitagenda.CrossfitAgendaService/CredentialsGoogle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossfitAgendaServiceClient) SetTokenGoogle(ctx context.Context, in *SetTokenGoogleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/crossfitagenda.CrossfitAgendaService/SetTokenGoogle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossfitAgendaServiceClient) StartCrossfitAgenda(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/crossfitagenda.CrossfitAgendaService/StartCrossfitAgenda", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crossfitAgendaServiceClient) Status(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Status200Response, error) {
	out := new(Status200Response)
	err := c.cc.Invoke(ctx, "/crossfitagenda.CrossfitAgendaService/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrossfitAgendaServiceServer is the server API for CrossfitAgendaService service.
// All implementations should embed UnimplementedCrossfitAgendaServiceServer
// for forward compatibility
type CrossfitAgendaServiceServer interface {
	CredentialsGoogle(context.Context, *emptypb.Empty) (*CredentialsGoogle200Response, error)
	SetTokenGoogle(context.Context, *SetTokenGoogleRequest) (*emptypb.Empty, error)
	StartCrossfitAgenda(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	Status(context.Context, *emptypb.Empty) (*Status200Response, error)
}

// UnimplementedCrossfitAgendaServiceServer should be embedded to have forward compatible implementations.
type UnimplementedCrossfitAgendaServiceServer struct {
}

func (UnimplementedCrossfitAgendaServiceServer) CredentialsGoogle(context.Context, *emptypb.Empty) (*CredentialsGoogle200Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CredentialsGoogle not implemented")
}
func (UnimplementedCrossfitAgendaServiceServer) SetTokenGoogle(context.Context, *SetTokenGoogleRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTokenGoogle not implemented")
}
func (UnimplementedCrossfitAgendaServiceServer) StartCrossfitAgenda(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartCrossfitAgenda not implemented")
}
func (UnimplementedCrossfitAgendaServiceServer) Status(context.Context, *emptypb.Empty) (*Status200Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}

// UnsafeCrossfitAgendaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrossfitAgendaServiceServer will
// result in compilation errors.
type UnsafeCrossfitAgendaServiceServer interface {
	mustEmbedUnimplementedCrossfitAgendaServiceServer()
}

func RegisterCrossfitAgendaServiceServer(s grpc.ServiceRegistrar, srv CrossfitAgendaServiceServer) {
	s.RegisterService(&CrossfitAgendaService_ServiceDesc, srv)
}

func _CrossfitAgendaService_CredentialsGoogle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossfitAgendaServiceServer).CredentialsGoogle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crossfitagenda.CrossfitAgendaService/CredentialsGoogle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossfitAgendaServiceServer).CredentialsGoogle(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossfitAgendaService_SetTokenGoogle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTokenGoogleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossfitAgendaServiceServer).SetTokenGoogle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crossfitagenda.CrossfitAgendaService/SetTokenGoogle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossfitAgendaServiceServer).SetTokenGoogle(ctx, req.(*SetTokenGoogleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossfitAgendaService_StartCrossfitAgenda_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossfitAgendaServiceServer).StartCrossfitAgenda(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crossfitagenda.CrossfitAgendaService/StartCrossfitAgenda",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossfitAgendaServiceServer).StartCrossfitAgenda(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrossfitAgendaService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossfitAgendaServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crossfitagenda.CrossfitAgendaService/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossfitAgendaServiceServer).Status(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CrossfitAgendaService_ServiceDesc is the grpc.ServiceDesc for CrossfitAgendaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrossfitAgendaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crossfitagenda.CrossfitAgendaService",
	HandlerType: (*CrossfitAgendaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CredentialsGoogle",
			Handler:    _CrossfitAgendaService_CredentialsGoogle_Handler,
		},
		{
			MethodName: "SetTokenGoogle",
			Handler:    _CrossfitAgendaService_SetTokenGoogle_Handler,
		},
		{
			MethodName: "StartCrossfitAgenda",
			Handler:    _CrossfitAgendaService_StartCrossfitAgenda_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _CrossfitAgendaService_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/crossfitAgenda/crossfitagenda.proto",
}
