name: ci proxy bot

on:
  merge_group:
  pull_request:
    paths:
      - 'proxybot/**'

jobs:
  check_proxy_changed_files:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    outputs:
      is_proxy_changed: ${{ steps.is_proxy_changed.outputs.HAS_CHANGES }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Set is_proxy_changed
        id: is_proxy_changed
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          has_changes=${{ contains(env.CHANGED_FILES, 'proxybot/') }}
          echo HAS_CHANGES=${has_changes} >> ${GITHUB_OUTPUT}

  check_proxy_vulns:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: check_proxy_changed_files
    steps:

      - name: golang vulnchecker
        if: needs.check_proxy_changed_files.outputs.is_proxy_changed == 'true'
        uses: golang/govulncheck-action@v1
        with:
          work-dir: ./proxybot
          go-version-file: ./proxybot/go.mod

  ci:
    runs-on: ubuntu-latest
    needs: check_proxy_changed_files
    if: needs.check_proxy_changed_files.outputs.is_proxy_changed == 'true'

    strategy:
      matrix:
        go-version: [ '1.21', '1.22' ]

    defaults:
      run:
        working-directory: ./proxybot

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test
        run: |
          make tests

  end:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Notify
        run: |
          if [ ${{ needs.ci.result }} == 'success' ]; then
            echo "All tests passed"
            exit 0
          else
            echo "Tests failed"
            exit 1
          fi