name: iaac_apply

on:
  push:
    branches:
      - master
    paths:
      - infra/**

jobs:

  terraform_apply:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
      id-token: write
      pull-requests: write

    defaults:
      run:
        working-directory: ./infra

    outputs:
      is_infra_changed: ${{ steps.is_infra_changed.outputs.HAS_CHANGES }}

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          version: '= 459.0.0'
          project_id: ${{ secrets.PROJECT_ID }}

      - run: |
          sudo curl -fL -o tfcmt.tar.gz https://github.com/suzuki-shunsuke/tfcmt/releases/download/${TFCMT_VERSION}/tfcmt_linux_amd64.tar.gz
          sudo tar -C /usr/bin -xzf ./tfcmt.tar.gz
        env:
          TFCMT_VERSION: v4.8.0

      - uses: hashicorp/setup-terraform@v3.1.1
        with:
          terraform_version: 1.6.6

      - run: terraform fmt
        continue-on-error: true

      - run: terraform init -input=false

      - run: |
          tfcmt apply -- terraform apply -input=false -auto-approve -lock=false -no-color
        timeout-minutes: 20
        env:
          TF_VAR_region: ${{ secrets.REGION }}
          TF_VAR_zone: ${{ secrets.ZONE }}
          TF_VAR_project_id: ${{ secrets.PROJECT_ID }}
          TF_VAR_key_file: ${{ steps.auth.outputs.credentials_file_path }}
          TF_VAR_billing_account: ${{ secrets.BILLING_PROJECT }}
          TF_VAR_proxy_app_backend_target: ${{ secrets.BACKEND_SERVICE_NAME }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.TERRAFORM_COMMENT_TOKEN }}
